project_id = "tbsoidmookberljbxgpt"

[functions.link-account]
verify_jwt = true

[functions.ip-blocker]
verify_jwt = false

[functions.tmdb-search]
verify_jwt = false

[functions.bulk-import]
verify_jwt = false
